services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    command: flask run --host=0.0.0.0 --port=8000
    volumes:
      - ./Game:/Game
    ports:
      - "9000:8000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
